# Generated by Django 5.0.3 on 2024-11-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=255)),
                ('about_details', models.TextField()),
                ('about_image', models.ImageField(upload_to='about/')),
                ('about_point_1_title', models.CharField(max_length=255)),
                ('about_point_1_details', models.TextField()),
                ('about_point_2_title', models.CharField(max_length=255)),
                ('about_point_2_details', models.TextField()),
                ('about_point_3_title', models.CharField(max_length=255)),
                ('about_point_3_details', models.TextField()),
                ('about_point_4_title', models.CharField(max_length=255)),
                ('about_point_4_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blogs/')),
                ('blog_sub_title', models.CharField(max_length=255)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_date', models.DateField()),
                ('blog_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_title', models.CharField(max_length=255)),
                ('challenge_image', models.ImageField(upload_to='challenges/')),
                ('challenge_1_title', models.CharField(max_length=255)),
                ('challenge_1_details', models.TextField()),
                ('challenge_2_title', models.CharField(max_length=255)),
                ('challenge_2_details', models.TextField()),
                ('challenge_3_title', models.CharField(max_length=255)),
                ('challenge_3_details', models.TextField()),
                ('challenge_4_title', models.CharField(max_length=255)),
                ('challenge_4_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_image', models.ImageField(upload_to='counter/')),
                ('count_1_title', models.CharField(max_length=255)),
                ('count_1_value', models.IntegerField()),
                ('count_2_title', models.CharField(max_length=255)),
                ('count_2_value', models.IntegerField()),
                ('count_3_title', models.CharField(max_length=255)),
                ('count_3_value', models.IntegerField()),
                ('count_4_title', models.CharField(max_length=255)),
                ('count_4_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='features/')),
                ('feature_title', models.CharField(max_length=255)),
                ('feature_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('project_title', models.CharField(max_length=255)),
                ('project_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255)),
                ('service_details', models.TextField()),
                ('service_image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_subtitle', models.CharField(max_length=255)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_details', models.TextField()),
                ('slider_image', models.ImageField(upload_to='sliders/')),
                ('slider_video_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_image', models.ImageField(upload_to='testimonials/')),
                ('client_position', models.CharField(max_length=255)),
                ('client_review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcu_title', models.CharField(max_length=255)),
                ('wcu_details', models.TextField()),
                ('wcu_image', models.ImageField(upload_to='why_choose_us/')),
            ],
        ),
    ]
