# Generated by Django 5.0.3 on 2024-11-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='wcu_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
