# Generated by Django 5.0.3 on 2024-11-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_about_about_image_alter_blog_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=100)),
                ('header_icon', models.ImageField(upload_to='')),
                ('header_heading', models.CharField(max_length=100)),
                ('header_point_1', models.CharField(max_length=50)),
                ('header_point_2', models.CharField(max_length=100)),
            ],
        ),
    ]
