# Generated by Django 5.0.3 on 2024-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_title', models.CharField(max_length=100)),
                ('testing_details', models.CharField(max_length=100)),
                ('testing_image', models.ImageField(upload_to='')),
                ('testing_title_1', models.CharField(max_length=100)),
                ('testing_value_1', models.IntegerField()),
                ('testing_title_2', models.CharField(max_length=100)),
                ('testing_value_2', models.IntegerField()),
                ('testing_title_3', models.CharField(max_length=100)),
                ('testing_value_3', models.IntegerField()),
                ('testing_title_4', models.CharField(max_length=100)),
                ('testing_value_4', models.IntegerField()),
            ],
        ),
    ]
