# Generated by Django 5.0.3 on 2024-11-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Midel',
        ),
    ]
