# Generated by Django 5.0.3 on 2024-11-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_time_midel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securitey_title', models.CharField(max_length=100)),
                ('securitey_subtitle_1', models.CharField(max_length=100)),
                ('securitey_details_1', models.CharField(max_length=100)),
                ('securitey_subtitle_2', models.CharField(max_length=100)),
                ('securitey_details_2', models.CharField(max_length=100)),
                ('securitey_subtitle_3', models.CharField(max_length=100)),
                ('securitey_details_3', models.CharField(max_length=100)),
            ],
        ),
    ]
