# Generated by Django 5.0.3 on 2024-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardsection_title', models.CharField(max_length=100)),
                ('cardsection_details', models.CharField(max_length=100)),
                ('cardsection_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
