# Generated by Django 5.0.3 on 2024-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cardsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsection',
            name='cardsection_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='midel',
            name='testing_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
