# Generated by Django 5.0.3 on 2024-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_cardsection_cardsection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_icon',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
