# Generated by Django 5.0.3 on 2024-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_servicesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midel',
            name='testing_title_2',
        ),
        migrations.RemoveField(
            model_name='midel',
            name='testing_title_3',
        ),
        migrations.RemoveField(
            model_name='midel',
            name='testing_title_4',
        ),
        migrations.RemoveField(
            model_name='midel',
            name='testing_value_2',
        ),
        migrations.RemoveField(
            model_name='midel',
            name='testing_value_3',
        ),
        migrations.RemoveField(
            model_name='midel',
            name='testing_value_4',
        ),
        migrations.AddField(
            model_name='midel',
            name='testing_image_2',
            field=models.ImageField(default=1, upload_to='static/'),
            preserve_default=False,
        ),
    ]
