# Generated by Django 5.0.3 on 2024-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_midel_testing_title_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_heading', models.CharField(max_length=100)),
                ('recent_image', models.ImageField(upload_to='static/')),
                ('recent_details', models.CharField(max_length=100)),
                ('recent_date', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Midel',
        ),
    ]
