# Generated by Django 5.0.3 on 2024-11-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_recentsection_delete_midel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentsection',
            name='recent_heading',
        ),
    ]
