# Generated by Django 5.0.3 on 2024-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_recentsection_recent_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featuredpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='static/')),
                ('featured_date', models.CharField(max_length=100)),
                ('featured_title', models.CharField(max_length=100)),
                ('featured_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recentsection',
            name='recent_date',
            field=models.CharField(max_length=100),
        ),
    ]
