# Generated by Django 5.0.3 on 2024-11-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_featuredpost_alter_recentsection_recent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_title', models.CharField(max_length=100)),
                ('categories_number', models.IntegerField()),
            ],
        ),
    ]
