# Generated by Django 5.0.3 on 2024-11-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Cate',
        ),
    ]
