# Generated by Django 5.0.3 on 2024-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_categories_cate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cate',
            new_name='Catepost',
        ),
        migrations.RenameField(
            model_name='catepost',
            old_name='categories_number',
            new_name='catepost_number',
        ),
        migrations.RenameField(
            model_name='catepost',
            old_name='categories_title',
            new_name='catepost_title',
        ),
    ]
