# Generated by Django 5.0.3 on 2024-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rename_cate_catepost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contcard_image', models.ImageField(upload_to='static/')),
                ('contcard_title', models.CharField(max_length=100)),
                ('contcard_icon', models.ImageField(upload_to='static/')),
                ('contcard_details', models.CharField(max_length=100)),
            ],
        ),
    ]
