# Generated by Django 5.0.3 on 2024-11-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_contcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footearse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footear_image', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
